version: '3.8'

volumes:
  db-data: {}

services:
  db:
    build:
      context: ./backend
      dockerfile: ./docker/postgres/Dockerfile
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: ./backend
      dockerfile: ./docker/django/Dockerfile
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    depends_on:
      - db
    command: ./docker/django/entrypoint.sh
